In [45]:
import torch
import numpy as np

### Basic Initialization

In [8]:
# Creates a matrix that is has no definite values (it is the values of the last memory spaces)
x = torch.empty(5, 3)

In [9]:
x

tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
        [8.4490e-39, 9.6429e-39, 1.0653e-38],
        [1.0469e-38, 4.2246e-39, 1.0378e-38],
        [9.6429e-39, 9.2755e-39, 9.7346e-39],
        [1.0745e-38, 1.0102e-38, 9.9184e-39]])

In [10]:
# Creates a random matrix of size 5x3
x = torch.rand(5,3)

In [11]:
x

tensor([[0.6524, 0.7092, 0.9968],
        [0.9480, 0.3084, 0.3857],
        [0.0628, 0.3226, 0.9769],
        [0.2596, 0.7725, 0.9289],
        [0.8505, 0.2935, 0.8611]])

In [18]:
# Creates and initalizes a matrix with 0s
x = torch.zeros(5, 3)

In [20]:
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
# Construct tensor directly from data
x = torch.tensor([5.0, 3])

In [28]:
x

tensor([5., 3.])

### Operations

In [29]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [32]:
# Addition
print(x + y)
print(torch.add(x, y))

tensor([[1.2492, 0.6759, 0.7531],
        [1.4139, 1.0459, 1.8802],
        [0.5806, 0.8386, 1.4044],
        [1.5312, 0.6494, 0.9338],
        [1.7696, 0.8694, 1.0481]])
tensor([[1.2492, 0.6759, 0.7531],
        [1.4139, 1.0459, 1.8802],
        [0.5806, 0.8386, 1.4044],
        [1.5312, 0.6494, 0.9338],
        [1.7696, 0.8694, 1.0481]])


In [34]:
# Indexing!
x

tensor([[0.5755, 0.6451, 0.2230],
        [0.5554, 0.7343, 0.9653],
        [0.4765, 0.3668, 0.8555],
        [0.8795, 0.3161, 0.8498],
        [0.8122, 0.5057, 0.8816]])

In [36]:
# Get only the second column
x[:, 1]

tensor([0.6451, 0.7343, 0.3668, 0.3161, 0.5057])

In [39]:
# For resizing/reshapig tensors, use torch.view
x = torch.randn(4, 4)

# Essentially making the one dimensional (could've also done x.view(-1) if the size of the matrix was unknown)
y = x.view(16) 

# the size -1 is inferred from other dimensions (in this case 16 / 8 is 2, so the dimension is 2)
z = x.view(-1, 8) 

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [40]:
# If you have a 1-element tensor, use item to get it as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0342])
1.0341938734054565


### Numpy Relationship
When converting a Torch Tensor to Numpy array (or vice versa), the two share the same underlying memory locations, so changing one will change the other

In [41]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [42]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [43]:
# Changing b changes a
b[0] = 234
a

tensor([234.,   1.,   1.,   1.,   1.])

In [44]:
# Changing a changes b
a[1] = 888
b

array([234., 888.,   1.,   1.,   1.], dtype=float32)

In [49]:
# From Numpy array to Torch Tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [50]:
# NOTE: If you want to keep it so that a and b share the same memory space, you *CANNOT* do a = a + 1.
# That allocates new memory and therefore a and b are not shared
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

In [51]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)